# Generated by Django 3.1.5 on 2021-03-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='batch',
            field=models.SmallIntegerField(default=0),
        ),
    ]
