# Generated by Django 3.1.5 on 2021-04-12 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210330_1229'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=100)),
                ('slotid', models.CharField(max_length=100)),
                ('notes', models.TextField(max_length=1000)),
            ],
        ),
    ]
