# Generated by Django 3.1.5 on 2021-05-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_algo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algo',
            name='subject_id',
            field=models.CharField(max_length=256),
        ),
    ]
