# Generated by Django 3.1.5 on 2021-05-05 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210504_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='algo',
            name='id',
        ),
        migrations.AlterField(
            model_name='algo',
            name='slot_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
