# Generated by Django 3.1.5 on 2021-05-06 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210505_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='algo',
            name='email',
            field=models.EmailField(default='ok@gmail.com', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='algo',
            name='subject_id',
            field=models.CharField(max_length=50),
        ),
    ]
