# Generated by Django 3.2 on 2021-05-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20210506_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='userid',
            field=models.IntegerField(),
        ),
    ]
